import argparse
import sys

def make_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('-l', '--list', dest='listfile', help='The list file (list of domains)')
    parser.add_argument('-a', '--allow', dest='allow', help='If you want to create a whitelist', action="store_true")
    parser.add_argument('-d', '--deny', dest='deny', help='If you want to create a blacklist', action="store_true")
    parser.add_argument('-t', '--type', dest='type', help='Type of list file (currently supported: urlblacklist)')

    return parser

def convert_list(options):
    if options.allow:
        aord = 'allow'
    if options.deny:
        aord = 'deny'
    fhl = open(options.listfile, 'r')
    fhr = open('result.rsc', 'w')
    fhr.write('# Generated by mktk-list-converter\n')
    fhr.write(":put \"Importing the web-proxy configuration\";\n")
    fhr.write('/ip proxy access\n')
    for line in fhl:
        fhr.write('add action=' + aord + ' disabled=no dst-host=*' + line)
    fhr.write(":put \"Import finished successfully\";")

def main(argv=None):

    # We default argv to None and assign to sys.argv[1:] below because having
    # an argument default value be a mutable type in Python is a gotcha. See
    # http://bit.ly/1o18Vff
    if argv is None:
        argv = sys.argv[1:]

    parser = make_parser()
    options = parser.parse_args(argv)
    if not options.listfile:
        parser.error("Must specify a 'list' file")
    if not (options.allow or options.deny):
        parser.error("Must specify 'allow' or 'deny'")
    if options.allow and options.deny:
        parser.error("Cannot specify both 'allow' and 'deny', it's one or the other")

    convert_list(options)

if __name__ == '__main__':
    sys.path.insert(0, '.')
    main()
